@startuml "architecture-design-client"

  skinparam {
    linetype ortho
    monochrome true
    ArrowColor black
    backgroundColor transparent
    classBackgroundColor transparent
    ' style strictuml
    actorBackgroundColor transparent
    componentBackgroundColor transparent
    padding 5
  }

  left to right direction

  ' actor :user: as user

  component [client] as react {
    database "Store" as store {
      component [editorSlice] as editor
      component [execSlice] as canvas
    }
    component [UI] as ui
    component [Middleware] as mw

    editor --> mw
    mw -up-> canvas
  }

  ' user --> ui
  ui --> editor
  ui <-- editor
  ui <-- canvas

@enduml
