@startuml "architecture-design-server"

  skinparam {
    linetype ortho
    monochrome true
    ArrowColor black
    backgroundColor transparent
    classBackgroundColor transparent
    ' style strictuml
    actorBackgroundColor transparent
    componentBackgroundColor transparent
    padding 5
  }

  left to right direction

  component [backend] {
    component [server] as vertx {
      component [BridgeVerticle] as bridge
      component [AlchemistVerticle] as exec

      bridge --> exec
      bridge <-- exec: EventBus
    }

    interface SockJS as sock

    sock -down- bridge

    component [executor] as alchemist

    exec -(0- alchemist
  }

@enduml
